### ISSUE TITLE
Compile errors in MicrosoftDemangleNodes.[h,cpp]

### ISSUE THREAD

**Issue by vkomenda** [Blaok/tapa#7]
GCC 11.2. Why is demangling MSVC symbols enabled on Linux?

Getting lots of errors such as
```
In file included from /home/vk/src/blaok/tapa/build/_deps/llvm-src/llvm/lib/Demangle/MicrosoftDemangleNodes.cpp:14:
/home/vk/src/blaok/tapa/build/_deps/llvm-src/llvm/include/llvm/Demangle/MicrosoftDemangleNodes.h:14:17: error: found ‘:’ in nested-name-specifier, expected ‘::’
   14 | enum Qualifiers : uint8_t {
      |                 ^
      |                 ::
/home/vk/src/blaok/tapa/build/_deps/llvm-src/llvm/include/llvm/Demangle/MicrosoftDemangleNodes.h:14:6: error: ‘Qualifiers’ has not been declared
   14 | enum Qualifiers : uint8_t {
      |      ^~~~~~~~~~
```

**Comment by Blaok** [comment]
That is part of LLVM. We use its clang part to perform some necessary source-to-source transformation. Apparently, clang depends on `MicrosoftDemangleNodes.cpp` for some reason, even we are compiling under Linux. Clearly, we won't be able to fix issues that are part of LLVM. Bumping LLVM version is only theoretically possible, and it requires a fairly significant amount of work that none of our developers can do right now. So, unfortunately, unless the current LLVM code becomes incompatible with a future Ubuntu LTS release, I don't think we will be able to spent time on this issue.

**Comment by Blaok** [comment]
BTW, this repo is for binary releases only; not many developers monitor the issues here. It'll be good if you could open new issues in https://github.com/UCLA-VAST/tapa.
